### ISSUE TITLE
Requests cannot handle dots '.'

### ISSUE THREAD

**Issue by jzush** [nirix/nanite#1]
Hi,

When POSTING or GETTING a value with a dot '.' in it, it is replaced with a underscore.

Example: http://x.com/user/google.com
Nanite gives the responds with : google_com

The issue has also been reports here: https://bugs.php.net/bug.php?id=30956

**Comment by nirix** [comment]
What is the exact PHP version you are running?

**Comment by jzush** [comment]
5.4.36

**Comment by nirix** [comment]
I installed PHP 5.4.36 and did `GET` and `POST` requests to `/test/domain.com` without any issues.

Would you be able to supply a snippet of code that demonstrates this issue along with the server URL rewriting rules?

**Comment by jzush** [comment]
```
     get('/members/([a-zA-Z0-9\-_]+)', function($user){

$frontpage = new Template("profile.tpl");

$frontpage->set("username", $user);

$layout = new Template("layout.tpl");
$layout->set("title", "Profile " . $user);

$layout->navi('account');

$layout->set("content", $frontpage->output());
echo $layout->output();

    });
```

When I use http://domain.com/members/google.com

The title of the page is returned as "Profile google_com" and also on the page itself it says "google_com"

**Comment by nirix** [comment]
Are you running nginx with PHP-FPM?

No issues with Apache 2.4 + PHP 5.4 and 5.5. However, I'm seeing the issue with nginx and PHP-FPM. Will have to figure out if there is a way to stop it from happening.

**Comment by jzush** [comment]
I'm running cPanel + Apache 2.2.29

**Comment by nirix** [comment]
Okay, did some testing.

Here are two rewrite rules that should work:

```
RewriteRule ^(.*)$ index.php/$1 [L,QSA]
# or
RewriteRule ^(.*)$ index.php?url=$1 [L,QSA]
```

**Comment by JayNZ** [comment]
RewriteRule ^(.*)$ index.php/$1 [L,QSA]

Works fine for non-dots "hello", but when using "google.com" the page appears white.

RewriteRule ^(.*)$ index.php?url=$1 [L,QSA

Kills the whole website apart from the frontpage.
