### ISSUE TITLE
Handling 404

### ISSUE THREAD

**Issue by jzush** [nirix/nanite#2]
How do I handle 404 (not found) errors?

Thanks.

**Comment by nirix** [comment]
The current way of handling 404 errors is to check if the route has been processed _after_ every other route.

``` php
<?php
get('/', ...);
get('/something/else', ...);
get('/something/different', ...);

....

// Now check if route has been processed
if (!Nanite::$routeProccessed) {
    // display 404
}
```

I would like to provide a proper way, such as `Nanite::set404(...)` but would also like to keep Nanite as small and fast as possible. I have a few ideas I've been playing around with and should have something soon.

**Comment by jzush** [comment]
Oh sweet. Thank you
