### ISSUE TITLE
Not working in subfolder

### ISSUE THREAD

**Issue by pixelbart** [nirix/nanite#3]
Hi!

I've a problem get nanite running in a subfolder.

domain.de/ -> other stuff
domain.de/subfolder/  -> Nanite Construct

Does not work. In the code i've found base_uri but is not used in the script.

Greetings

**Comment by leotop** [comment]
.htaccess add line after RewriteEngine On

RewriteBase /subfolder/

Example:
```
RewriteEngine On
RewriteBase /subfolder/

RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ index.php/$1 [L,QSA]
```

**Comment by pixelbart** [comment]
Thanks leotop! Have fix it for my self for a long time ago 💃 But your solution was/is the correct one!
